	/*
	 * items in minecraft 1.12
	 */
	{id: 256, state: 0, name: "Iron Shovel",          stack: 1, cat: ALLCAT,   tex: [ 4, 5], durability: IRON},
	{id: 257, state: 0, name: "Iron Pickaxe",         stack: 1, cat: ALLCAT,   tex: [ 4, 6], durability: IRON},
	{id: 258, state: 0, name: "Iron Axe",             stack: 1, cat: ALLCAT,   tex: [ 4, 7], durability: IRON},
	{id: 259, state: 0, name: "Flint and Steel",      stack: 1, cat: ALLCAT,   tex: [ 8,13], durability: 64},
	{id: 260, state: 0, name: "Apple",                stack:64, cat: CROPS,    tex: [12, 0]},
	{id: 261, state: 0, name: "Bow",                  stack: 1, cat: ALLCAT,   tex: [ 0, 5], durability: 384},
	{id: 262, state: 0, name: "Arrow",                stack:64, cat: ALLCAT,   tex: [ 1, 4]},
	{id: 263, state: 0, name: "Coal",                 stack:64, cat: ALLCAT,   tex: [ 9, 1]},
	{id: 263, state: 1, name: "Charcoal",             stack:64, cat: ALLCAT,   tex: [ 9, 0], tech: "charcoal"},
	{id: 264, state: 0, name: "Diamond",              stack:64, cat: ALLCAT,   tex: [ 7, 0]},
	{id: 265, state: 0, name: "Iron Ingot",           stack:64, cat: ALLCAT,   tex: [ 8, 1]},
	{id: 266, state: 0, name: "Gold Ingot",           stack:64, cat: ALLCAT,   tex: [ 8, 2]},
	{id: 267, state: 0, name: "Iron Sword",           stack:64, cat: ALLCAT,   tex: [ 4, 4]},
	{id: 268, state: 0, name: "Wooden Sword",         stack: 1, cat: ALLCAT,   tex: [ 2, 4], durability: WOOD},
	{id: 269, state: 0, name: "Wooden Shovel",        stack: 1, cat: ALLCAT,   tex: [ 2, 5], durability: WOOD},
	{id: 270, state: 0, name: "Wooden Pickaxe",       stack: 1, cat: ALLCAT,   tex: [ 2, 6], durability: WOOD},
	{id: 271, state: 0, name: "Wooden Axe",           stack: 1, cat: ALLCAT,   tex: [ 2, 7], durability: WOOD},
	{id: 272, state: 0, name: "Stone Sword",          stack: 1, cat: ALLCAT,   tex: [ 3, 4], durability: STONE},
	{id: 273, state: 0, name: "Stone Shovel",         stack: 1, cat: ALLCAT,   tex: [ 3, 5], durability: STONE},
	{id: 274, state: 0, name: "Stone Pickaxe",        stack: 1, cat: ALLCAT,   tex: [ 3, 6], durability: STONE},
	{id: 275, state: 0, name: "Stone Axe",            stack: 1, cat: ALLCAT,   tex: [ 3, 7], durability: STONE},
	{id: 276, state: 0, name: "Diamond Sword",        stack: 1, cat: ALLCAT,   tex: [ 5, 4], durability: DIAMOND},
	{id: 277, state: 0, name: "Diamond Shovel",       stack: 1, cat: ALLCAT,   tex: [ 5, 5], durability: DIAMOND},
	{id: 278, state: 0, name: "Diamond Pickaxe",      stack: 1, cat: ALLCAT,   tex: [ 5, 6], durability: DIAMOND},
	{id: 279, state: 0, name: "Diamond Axe",          stack: 1, cat: ALLCAT,   tex: [ 5, 7], durability: DIAMOND},
	{id: 280, state: 0, name: "Stick",                stack:64, cat: ALLCAT,   tex: [ 1, 5]},
	{id: 281, state: 0, name: "Bowl",                 stack:64, cat: CROPS,    tex: [13,13]},
	{id: 282, state: 0, name: "Mushroom Stew",        stack: 1, cat: ALLCAT,   tex: [14,13]},
	{id: 283, state: 0, name: "Gold Sword",           stack: 1, cat: ALLCAT,   tex: [ 6, 4], durability: GOLD},
	{id: 284, state: 0, name: "Gold Shovel",          stack: 1, cat: ALLCAT,   tex: [ 6, 5], durability: GOLD},
	{id: 285, state: 0, name: "Gold Pickaxe",         stack: 1, cat: ALLCAT,   tex: [ 6, 6], durability: GOLD},
	{id: 286, state: 0, name: "Gold Axe",             stack: 1, cat: ALLCAT,   tex: [ 6, 7], durability: GOLD},
	{id: 287, state: 0, name: "String",               stack:64, cat: REDSTONE, tex: [10, 6], createBlock: "tripwire"},
	{id: 288, state: 0, name: "Feather",              stack:64, cat: ALLCAT,   tex: [14, 6]},
	{id: 289, state: 0, name: "Gunpowder",            stack:64, cat: ALLCAT,   tex: [ 8, 3]},
	{id: 290, state: 0, name: "Wooden Hoe",           stack: 1, cat: ALLCAT,   tex: [ 2, 8], durability: WOOD},
	{id: 291, state: 0, name: "Stone Hoe",            stack: 1, cat: ALLCAT,   tex: [ 3, 8], durability: STONE},
	{id: 292, state: 0, name: "Iron Hoe",             stack: 1, cat: ALLCAT,   tex: [ 4, 8], durability: IRON},
	{id: 293, state: 0, name: "Diamond Hoe",          stack: 1, cat: ALLCAT,   tex: [ 5, 8], durability: DIAMOND},
	{id: 294, state: 0, name: "Gold Hoe",             stack: 1, cat: ALLCAT,   tex: [ 6, 8], durability: GOLD},
	{id: 295, state: 0, name: "Wheat seeds",          stack:64, cat: CROPS,    tex: [14, 5], createBlock: "wheat"},
	{id: 296, state: 0, name: "Wheat",                stack:64, cat: CROPS,    tex: [15, 5]},
	{id: 297, state: 0, name: "Bread",                stack:64, cat: CROPS,    tex: [15, 6]},
	{id: 298, state: 0, name: "Leather Helmet",       stack: 1, cat: ALLCAT,   tex: [ 2, 0], durability: 55},
	{id: 299, state: 0, name: "Leather Chestplate",   stack: 1, cat: ALLCAT,   tex: [ 2, 1], durability: 80},
	{id: 300, state: 0, name: "Leather Leggings",     stack: 1, cat: ALLCAT,   tex: [ 2, 2], durability: 75},
	{id: 301, state: 0, name: "Leather Boots",        stack: 1, cat: ALLCAT,   tex: [ 2, 3], durability: 65},
	{id: 302, state: 0, name: "Chainmail Helmet",     stack: 1, cat: ALLCAT,   tex: [ 3, 0], durability: 165},
	{id: 303, state: 0, name: "Chainmail Chestplate", stack: 1, cat: ALLCAT,   tex: [ 3, 1], durability: 240},
	{id: 304, state: 0, name: "Chainmail Leggings",   stack: 1, cat: ALLCAT,   tex: [ 3, 2], durability: 225},
	{id: 305, state: 0, name: "Chainmail Boots",      stack: 1, cat: ALLCAT,   tex: [ 3, 3], durability: 195},
	{id: 306, state: 0, name: "Iron Helmet",          stack: 1, cat: ALLCAT,   tex: [ 4, 0], durability: 165},
	{id: 307, state: 0, name: "Iron Chestplate",      stack: 1, cat: ALLCAT,   tex: [ 4, 1], durability: 240},
	{id: 308, state: 0, name: "Iron Leggings",        stack: 1, cat: ALLCAT,   tex: [ 4, 2], durability: 225},
	{id: 309, state: 0, name: "Iron Boots",           stack: 1, cat: ALLCAT,   tex: [ 4, 3], durability: 195},
	{id: 310, state: 0, name: "Diamond Helmet",       stack: 1, cat: ALLCAT,   tex: [ 5, 0], durability: 363},
	{id: 311, state: 0, name: "Diamond Chestplate",   stack: 1, cat: ALLCAT,   tex: [ 5, 1], durability: 528},
	{id: 312, state: 0, name: "Diamond Leggings",     stack: 1, cat: ALLCAT,   tex: [ 5, 2], durability: 495},
	{id: 313, state: 0, name: "Diamond Boots",        stack: 1, cat: ALLCAT,   tex: [ 5, 3], durability: 429},
	{id: 314, state: 0, name: "Gold Helmet",          stack: 1, cat: ALLCAT,   tex: [ 6, 0], durability: 77},
	{id: 315, state: 0, name: "Gold Chestplate",      stack: 1, cat: ALLCAT,   tex: [ 6, 1], durability: 112},
	{id: 316, state: 0, name: "Gold Leggings",        stack: 1, cat: ALLCAT,   tex: [ 6, 2], durability: 105},
	{id: 317, state: 0, name: "Gold Boots",           stack: 1, cat: ALLCAT,   tex: [ 6, 3], durability: 91},
	{id: 318, state: 0, name: "Flint",                stack:64, cat: ALLCAT,   tex: [11, 4]},
	{id: 319, state: 0, name: "Raw Porkchop",         stack:64, cat: CROPS,    tex: [12, 4], tech: "porkchop"},
	{id: 320, state: 0, name: "Cooked Porkchop",      stack:64, cat: CROPS,    tex: [13, 4]},
	{id: 321, state: 0, name: "Painting",             stack:64, cat: DECO,     tex: [12,10], createTileEntity: "painting"},
	{id: 322, state: 0, name: "Golden apple",         stack:64, cat: CROPS,    tex: [13, 0]},
	{id: 322, state: 1, name: "Enchanted apple",      stack:64, cat: CROPS,    tex: [13, 0]},
	{id: 323, state: 0, name: "Sign",                 stack:16, cat: DECO,     tex: [11,10], createBlock: "wall_sign", createTileEntity: "sign"}, /* block 63 or 68 */
	{id: 324, state: 0, name: "Wooden door",          stack:16, cat: REDSTONE, tex: [ 0,13], createBlock: "wooden_door"},
	{id: 325, state: 0, name: "Bucket",               stack:16, cat: ALLCAT,   tex: [10, 0]},
	{id: 326, state: 0, name: "Water bucket",         stack: 1, cat: ALLCAT,   tex: [11, 0], createBlock: "water"},
	{id: 327, state: 0, name: "Lava bucket",          stack: 1, cat: ALLCAT,   tex: [10, 1], createBlock: "lava"},
	{id: 328, state: 0, name: "Minecart",             stack: 1, cat: RAILS,    tex: [ 1, 9]},
	{id: 329, state: 0, name: "Saddle",               stack: 1, cat: ALLCAT,   tex: [15, 7]},
	{id: 330, state: 0, name: "Iron door",            stack:16, cat: REDSTONE, tex: [ 1,13], createBlock: "iron_door"},
	{id: 331, state: 0, name: "Redstone dust",        stack:64, cat: REDSTONE, tex: [10, 3], createBlock: "redstone_wire", tech: "redstone"},
	{id: 332, state: 0, name: "Snowball",             stack:16, cat: DECO,     tex: [ 9, 6]},
	{id: 333, state: 0, name: "Boat",                 stack: 1, cat: ALLCAT,   tex: [ 0, 9]},
	{id: 334, state: 0, name: "Leather",              stack:64, cat: ALLCAT,   tex: [14, 7]},
	{id: 335, state: 0, name: "Milk Bucket",          stack: 1, cat: ALLCAT,   tex: [11, 1]},
	{id: 336, state: 0, name: "Clay Brick",           stack:64, cat: ALLCAT,   tex: [ 7, 1], tech: "brick"},
	{id: 337, state: 0, name: "Clay",                 stack:64, cat: ALLCAT,   tex: [11, 3], tech: "clay_ball"},
	{id: 338, state: 0, name: "Sugar Cane (reeds)",   stack:64, cat: CROPS,    tex: [12, 8], tech: "reeds", createBlock: "sugar_cane"},
	{id: 339, state: 0, name: "Paper",                stack:64, cat: ALLCAT,   tex: [13, 8]},
	{id: 340, state: 0, name: "Book",                 stack:64, cat: ALLCAT,   tex: [14, 9]},
	{id: 341, state: 0, name: "Slime Ball",           stack:64, cat: ALLCAT,   tex: [ 8, 7], tech: "slimeball"},
	{id: 342, state: 0, name: "Chest Minecart",       stack: 1, cat: RAILS,    tex: [ 2, 9]},
	{id: 343, state: 0, name: "Furnace Minecart",     stack: 1, cat: RAILS,    tex: [ 3, 9]},
	{id: 344, state: 0, name: "Egg",                  stack:16, cat: CROPS,    tex: [ 7, 5]},
	{id: 345, state: 0, name: "Compass",              stack:64, cat: ALLCAT,   tex: [ 7,10]},
	{id: 346, state: 0, name: "Fishing Rod",          stack: 1, cat: ALLCAT,   tex: [ 1, 7]},
	{id: 347, state: 0, name: "Clock",                stack:64, cat: ALLCAT,   tex: [ 8,10]},
	{id: 348, state: 0, name: "Glowstone Dust",       stack:64, cat: DECO,     tex: [ 7, 3]},
	{id: 349, state: 0, name: "Raw Fish",             stack:64, cat: CROPS,    tex: [12, 6], tech: "fish"},
	{id: 349, state: 1, name: "Raw Salmon",           stack:64, cat: CROPS,    tex: [12, 6]}, // XXX
	{id: 349, state: 2, name: "Clownfish",            stack:64, cat: CROPS,    tex: [12, 6]}, // XXX
	{id: 349, state: 3, name: "PufferFish",           stack:64, cat: CROPS,    tex: [12, 6]}, // XXX
	{id: 350, state: 0, name: "Cooked Fish",          stack:64, cat: CROPS,    tex: [13, 6], tech: "cooked_fished"},
	{id: 350, state: 1, name: "Cooked Salmon",        stack:64, cat: DECO,     tex: [13, 6]},
	{id: 351, state: 0, name: "Ink Sac",              stack:64, cat: DECO,     tex: [ 3,12], tech: "dye"},
	{id: 351, state: 1, name: "Rose Red Dye",         stack:64, cat: DECO,     tex: [ 5,12]},
	{id: 351, state: 2, name: "Cactus Green Dye",     stack:64, cat: DECO,     tex: [12,12]},
	{id: 351, state: 3, name: "Cocoa Bean",           stack:64, cat: CROPS,    tex: [15,12], createBlock: "cocoa_beans"},
	{id: 351, state: 4, name: "Lapis Lazuli",         stack:64, cat: DECO,     tex: [ 9,12]},
	{id: 351, state: 5, name: "Purple Dye",           stack:64, cat: DECO,     tex: [ 6,12]},
	{id: 351, state: 6, name: "Cyan Dye",             stack:64, cat: DECO,     tex: [10,12]},
	{id: 351, state: 7, name: "Light Gray Dye",       stack:64, cat: DECO,     tex: [ 1,12]},
	{id: 351, state: 8, name: "Gray Dye",             stack:64, cat: DECO,     tex: [ 2,12]},
	{id: 351, state: 9, name: "Pink Dye",             stack:64, cat: DECO,     tex: [ 4,12]},
	{id: 351,state: 10, name: "Lime Dye",             stack:64, cat: DECO,     tex: [11,12]},
	{id: 351,state: 11, name: "Dandelion Yellow Dye", stack:64, cat: DECO,     tex: [13,12]},
	{id: 351,state: 12, name: "Light Blue Dye",       stack:64, cat: DECO,     tex: [ 8,12]},
	{id: 351,state: 13, name: "Magenta Dye",          stack:64, cat: DECO,     tex: [ 7,12]},
	{id: 351,state: 14, name: "Orange Dye",           stack:64, cat: DECO,     tex: [14,12]},
	{id: 351,state: 15, name: "Bone Meal",            stack:64, cat: CROPS,    tex: [ 0,12]},
	{id: 352, state: 0, name: "Bone",                 stack:64, cat: ALLCAT,   tex: [11, 6]},
	{id: 353, state: 0, name: "Sugar",                stack:64, cat: CROPS,    tex: [ 9, 3]},
	{id: 354, state: 0, name: "Cake",                 stack: 1, cat: CROPS,    tex: [15, 1], createblock: "cake"},
	{id: 355, state: 0, name: "Bed",                  stack: 1, cat: DECO,     tex: [10,10], createblock: "bed"},
	{id: 356, state: 0, name: "Redstone Repeater",    stack:64, cat: REDSTONE, tex: [10, 2], createblock: "unpowered_repeater", tech: "repeater"},
	{id: 357, state: 0, name: "Cookie",               stack:64, cat: CROPS,    tex: [15, 2]},
	{id: 358, state: 0, name: "Map",                  stack:64, cat: ALLCAT,   tex: [15, 8], tech: "filled_map"},
	{id: 359, state: 0, name: "Shears",               stack: 1, cat: ALLCAT,   tex: [ 7,13], durability: 238},
	{id: 360, state: 0, name: "Melon (Slice)",        stack:64, cat: CROPS,    tex: [12, 3], tech: "melon"},
	{id: 361, state: 0, name: "Pumpkin Seeds",        stack:64, cat: CROPS,    tex: [14, 4]},
	{id: 362, state: 0, name: "Melon Seeds",          stack:64, cat: CROPS,    tex: [14, 3]},
	{id: 363, state: 0, name: "Raw Beef",             stack:64, cat: CROPS,    tex: [12, 5], tech: "beef"},
	{id: 364, state: 0, name: "Steak",                stack:64, cat: CROPS,    tex: [13, 5], tech: "cooked_beef"},
	{id: 365, state: 0, name: "Raw Chicken",          stack:64, cat: CROPS,    tex: [12, 7], tech: "chicken"},
	{id: 366, state: 0, name: "Cooked Chicken",       stack:64, cat: CROPS,    tex: [13, 7]},
	{id: 367, state: 0, name: "Rotten Flesh",         stack:64, cat: ALLCAT,   tex: [14, 1]},
	{id: 368, state: 0, name: "Ender Pearl",          stack:16, cat: ALLCAT,   tex: [ 8, 8]},
	{id: 369, state: 0, name: "Blaze Rod",            stack:64, cat: ALLCAT,   tex: [ 9, 9]},
	{id: 370, state: 0, name: "Ghast Tear",           stack:64, cat: ALLCAT,   tex: [10, 7]},
	{id: 371, state: 0, name: "Gold Nugget",          stack:64, cat: ALLCAT,   tex: [ 9, 2]},
	{id: 372, state: 0, name: "Nether Wart",          stack:64, cat: CROPS,    tex: [15, 0]},
	{id: 373, state: 0, name: "Water bottle",         stack: 1, cat: ALLCAT,   tex: [10, 8], tech: "potion"}, // XXX
	{id: 374, state: 0, name: "Glass Bottle",         stack:64, cat: ALLCAT,   tex: [ 7, 9]},
	{id: 375, state: 0, name: "Spider Eye",           stack:64, cat: ALLCAT,   tex: [10, 5]},
	{id: 376, state: 0, name: "Fermented Spider Eye", stack:64, cat: ALLCAT,   tex: [11, 5]},
	{id: 377, state: 0, name: "Blaze Powder",         stack:64, cat: ALLCAT,   tex: [ 8, 9]},
	{id: 378, state: 0, name: "Magma Cream",          stack:64, cat: ALLCAT,   tex: [ 9, 7]},
	{id: 379, state: 0, name: "Brewing Stand",        stack:64, cat: REDSTONE, tex: [11, 7]},
	{id: 380, state: 0, name: "Cauldron",             stack:64, cat: REDSTONE, tex: [ 7, 7], createBlock: "cauldron"},
	{id: 381, state: 0, name: "Eye of Ender",         stack:64, cat: ALLCAT,   tex: [ 9, 8], tech: "ender_eye"},
	{id: 382, state: 0, name: "Glistering Melon",     stack:64, cat: ALLCAT,   tex: [13, 3], tech: "speckled_melon"},
	{id: 384, state: 0, name: "Bottle of XP",         stack:64, cat: ALLCAT,   tex: [11, 8], tech: "experience_bottle"},
	{id: 385, state: 0, name: "Fire Charge",          stack:64, cat: ALLCAT,   tex: [ 8, 6]},
	{id: 386, state: 0, name: "Book and Quill",       stack: 1, cat: ALLCAT,   tex: [15,10], tech: "writable_book"},
	{id: 387, state: 0, name: "Written Book",         stack: 1, cat: ALLCAT,   tex: [14,10]},
	/* minecraft 1.3 */
	{id: 388, state: 0, name: "Emerald",              stack:64, cat: ALLCAT,   tex: [ 8, 0]},
	{id: 389, state: 0, name: "Item Frame",           stack:64, cat: ALLCAT,   tex: [13,10]},
	{id: 390, state: 0, name: "Flower Pot",           stack:64, cat: ALLCAT,   tex: [15, 3], createBlock: "flower_pot"},
	{id: 391, state: 0, name: "Carrot",               stack:64, cat: CROPS,    tex: [12, 1], createBlock: "carrots"},
	{id: 392, state: 0, name: "Potato",               stack:64, cat: CROPS,    tex: [12, 2], createBlock: "potatoes"},
	{id: 393, state: 0, name: "Baked potato",         stack:64, cat: CROPS,    tex: [13, 2]},
	{id: 394, state: 0, name: "Poisonous Potato",     stack:64, cat: CROPS,    tex: [14, 2]},
	{id: 395, state: 0, name: "Empty Map",            stack:64, cat: ALLCAT,   tex: [14, 8], tech: "map"},
	{id: 396, state: 0, name: "Golden Carrot",        stack:64, cat: CROPS,    tex: [13, 1]},
	{id: 397, state: 0, name: "Head (skeleton)",      stack:64, cat: ALLCAT,   tex: [ 2,10], tech: "skull"},
	{id: 397, state: 1, name: "Head (wither)",        stack:64, cat: ALLCAT,   tex: [ 3,10]},
	{id: 397, state: 2, name: "Head (zombie)",        stack:64, cat: ALLCAT,   tex: [ 4,10]},
	{id: 397, state: 3, name: "Head (steve)",         stack:64, cat: ALLCAT,   tex: [ 5,10]},
	{id: 397, state: 4, name: "Head (creeper)",       stack:64, cat: ALLCAT,   tex: [ 6,10]},
	{id: 398, state: 0, name: "Carrot on a stick",    stack: 1, cat: ALLCAT,   tex: [ 1, 8]},
	{id: 399, state: 0, name: "Nether Star",          stack:64, cat: ALLCAT,   tex: [ 7, 6]},
	{id: 400, state: 0, name: "Pumpkin Pie",          stack:64, cat: CROPS,    tex: [15, 4]},
	{id: 401, state: 0, name: "Firework Rocket",      stack:64, cat: ALLCAT,   tex: [ 7, 4], tech: "fireworks"},
	{id: 402, state: 0, name: "Firework Charge",      stack:64, cat: ALLCAT,   tex: [ 8, 4]},
	{id: 403, state: 0, name: "Enchanted Book",       stack: 1, cat: ALLCAT,   tex: [15, 9]},
	{id: 404, state: 0, name: "Comparator",           stack:64, cat: REDSTONE, tex: [11, 2]},
	{id: 405, state: 0, name: "Nether Brick",         stack:64, cat: ALLCAT,   tex: [ 7, 2], tech: "netherbrick"},
	{id: 406, state: 0, name: "Nether Quartz",        stack:64, cat: REDSTONE, tex: [14, 0], tech: "quartz"},
	{id: 407, state: 0, name: "TNT Minecart",         stack: 1, cat: RAILS,    tex: [ 0,10]},
	{id: 408, state: 0, name: "Hopper Minecart",      stack: 1, cat: REDSTONE, tex: [ 1,10]},
	/* minecraft 1.8 */
	{id: 409, state: 0, name: "Prismarine Shard",     stack:64, cat: ALLCAT,   tex: [ 0, 0]}, // XXX
	{id: 410, state: 0, name: "Prismarine Crystals",  stack:64, cat: ALLCAT,   tex: [ 0, 0]}, // XXX
	{id: 411, state: 0, name: "Raw Rabbit",           stack:64, cat: CROPS,    tex: [ 9,13], tech: "rabbit"},
	{id: 412, state: 0, name: "Cooked Rabbit",        stack:64, cat: CROPS,    tex: [10,13]},
	{id: 413, state: 0, name: "Rabbit Stew",          stack: 1, cat: CROPS,    tex: [11,13]},
	{id: 414, state: 0, name: "Rabbit Foot",          stack:64, cat: ALLCAT,   tex: [ 0, 0]}, // XXX
	{id: 415, state: 0, name: "Rabbit Hide",          stack:64, cat: ALLCAT,   tex: [ 0, 0]}, // XXX
	{id: 416, state: 0, name: "Armor Stand",          stack:16, cat: ALLCAT,   tex: [ 0, 0]}, // XXX
	{id: 417, state: 0, name: "Iron Horse Armor",     stack: 1, cat: ALLCAT,   tex: [ 4, 9]},
	{id: 418, state: 0, name: "Golden Horse Armor",   stack: 1, cat: ALLCAT,   tex: [ 5, 9]},
	{id: 419, state: 0, name: "Diamond Horse Armor",  stack: 1, cat: ALLCAT,   tex: [ 6, 9]},
	{id: 420, state: 0, name: "Lead",                 stack:64, cat: ALLCAT,   tex: [13,11]},
	{id: 421, state: 0, name: "Name Tag",             stack:64, cat: ALLCAT,   tex: [12,11]},
	{id: 422, state: 0, name: "Minecart Command",     stack: 1, cat: REDSTONE, tex: [ 0, 0]}, // XXX
	{id: 423, state: 0, name: "Raw Mutton",           stack:64, cat: CROPS,    tex: [12, 9], tech: "mutton"},
	{id: 424, state: 0, name: "Cooked Mutton",        stack:64, cat: CROPS,    tex: [13, 9]},
	{id: 425, state: 0, name: "Banner",               stack:16, cat: ALLCAT,   tex: [ 0, 0]}, // XXX
	{id: 426, state: 0, name: "End Crystal",          stack:64, cat: ALLCAT,   tex: [ 9,13]},
	{id: 427, state: 0, name: "Spruce Door",          stack:16, cat: REDSTONE, tex: [ 2,13], createBlock: "spruce_door"},
	{id: 428, state: 0, name: "Birch Door",           stack:16, cat: REDSTONE, tex: [ 3,13], createBlock: "birch_door"},
	{id: 429, state: 0, name: "Jungle Door",          stack:16, cat: REDSTONE, tex: [ 6,13], createBlock: "jungle_door"},
	{id: 430, state: 0, name: "Acacia Door",          stack:16, cat: REDSTONE, tex: [ 4,13], createBlock: "acacia_door"},
	{id: 431, state: 0, name: "Dark Oak Door",        stack:16, cat: REDSTONE, tex: [ 5,13], createBlock: "dark_oak_door"},
	{id: 432, state: 0, name: "Chorus Fruit",         stack:64, cat: CROPS,    tex: [ 0, 0]}, // XXX
	{id: 433, state: 0, name: "Popped Chorus Fruit",  stack:64, cat: CROPS,    tex: [ 0, 0], tech: "chorus_fruit_popped"},
	{id: 434, state: 0, name: "Beetroot",             stack:64, cat: CROPS,    tex: [ 0, 0]}, // XXX
	{id: 435, state: 0, name: "Beetroot Seeds",       stack:64, cat: CROPS,    tex: [ 9, 4]},
	{id: 436, state: 0, name: "Beetroot Soup",        stack: 1, cat: CROPS,    tex: [12,13]},
	{id: 437, state: 0, name: "Dragon's Breath",      stack:16, cat: ALLCAT,   tex: [ 0, 0], tech: "dragon_breath"}, // XXX
	{id: 439, state: 0, name: "Arrow (Spectral)",     stack:64, cat: ALLCAT,   tex: [ 0, 0], tech: "spectral_arrow"}, // XXX
	{id: 442, state: 0, name: "Shield",               stack: 1, cat: ALLCAT,   tex: [ 0, 0], durability: 336}, // XXX
	{id: 443, state: 0, name: "Elytra",               stack: 1, cat: ALLCAT,   tex: [ 0, 0], durability: 432},
	{id: 449, state: 0, name: "Totem of Undying",     stack: 1, cat: ALLCAT,   tex: [15,13], tech: "totem"},
	{id: 450, state: 0, name: "Shulker Shell",        stack:64, cat: ALLCAT,   tex: [ 0, 0]}, // XXX
	{id: 2256, state: 0, name: "Music Disc (13)",     stack: 1, cat: DECO,     tex: [ 0,11], tech: "record_13"},
	{id: 2257, state: 0, name: "Music Disc (Cat)",    stack: 1, cat: DECO,     tex: [ 1,11], tech: "record_cat"},
	{id: 2258, state: 0, name: "Music Disc (Blocks)", stack: 1, cat: DECO,     tex: [ 2,11], tech: "record_blocks"},
	{id: 2259, state: 0, name: "Music Disc (Chirp)",  stack: 1, cat: DECO,     tex: [ 3,11], tech: "record_chirp"},
	{id: 2260, state: 0, name: "Music Disc (Far)",    stack: 1, cat: DECO,     tex: [ 4,11], tech: "record_far"},
	{id: 2261, state: 0, name: "Music Disc (Mall)",   stack: 1, cat: DECO,     tex: [ 5,11], tech: "record_mall"},
	{id: 2262, state: 0, name: "Music Disc (Mellohi)",stack: 1, cat: DECO,     tex: [ 6,11], tech: "record_mellohi"},
	{id: 2263, state: 0, name: "Music Disc (Stal)",   stack: 1, cat: DECO,     tex: [ 7,11], tech: "record_stal"},
	{id: 2264, state: 0, name: "Music Disc (Strad)",  stack: 1, cat: DECO,     tex: [ 8,11], tech: "record_strad"},
	{id: 2265, state: 0, name: "Music Disc (Ward)",   stack: 1, cat: DECO,     tex: [ 9,11], tech: "record_ward"},
	{id: 2266, state: 0, name: "Music Disc (11)",     stack: 1, cat: DECO,     tex: [10,11], tech: "record_11"},
	{id: 2267, state: 0, name: "Music Disc (Wait)",   stack: 1, cat: DECO,     tex: [11,11], tech: "record_wait"},
